---
# tasks file for terminator

- name: install golang
  command: "{{ item }}"
  with_items:
    - apt-get install golang -y
    - mkdir -p "/home/{{ ansible_user }}/Go"

- name: put config golang in bashrc
  lineinfile:
    path: "/home/{{ ansible_user }}/.bashrc"
    insertafter: EOF
    line: "{{ item }}"
  with_items:
    - export GOPATH=~/Go
    - export PATH=$PATH:$GOPATH/bin
