---
# tasks file for terminator

- name: install golang
  command: "{{ item }}"
  with_items:
    - apt-get install golang -y

- file:
    path: "/home/{{ ansible_user }}/Go"
    state: directory
    mode: 0755
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: put config golang in bashrc
  lineinfile:
    path: "/home/{{ ansible_user }}/.bashrc"
    insertafter: EOF
    line: "{{ item }}"
  with_items:
    - export GOPATH=~/Go
    - export PATH=$PATH:$GOPATH/bin
