---
# tasks file for terminator

- name: install generics packets
  command: "{{ item }}"
  with_items:
    - apt-get install curl python3-dev python3-pip -y

- name: install fuck
  command: "{{ item }}"
  with_items:
    - pip3 install thefuck

