---
# tasks file for terminator

- name: install generics packets with apt
  command: "{{ item }}"
  with_items:
    - apt-get install curl python3-dev python3-pip openconnect -y

- name: install generics packets with pip3
  command: "{{ item }}"
  with_items:
    - pip3 install thefuck
    - pip install ansible
  become: false

