---
# tasks file for terminator

- name: install terminator
  command: "{{ item }}"
  with_items:
    - apt-get install terminator

- name: copy template config
  template:
    src: config.j2
    dest: "/home/{{ ansible_user }}/.config/terminator/config"

