---
# tasks file for docker

- name: uninstall docker
  command: "{{ item }}"
  with_items:
    - apt-get remove docker docker-engine docker.io
    - apt-get install apt-transport-https ca-certificates curl software-properties-common
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    - apt-get update
    - apt-get install docker-ce

- name: copy template config
  template:
    src: daemon.json.j2
    dest: "/etc/docker/daemon.json"

