---
# tasks file for docker

- name: uninstall docker
  command: "{{ item }}"
  with_items:
    - apt-get remove docker docker-engine docker.io -y

- name: install pre-packet
  command: "{{ item }}"
  with_items:
    - apt-get install apt-transport-https ca-certificates curl software-properties-common -y

- name: add repo docker
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

- name: apt update
  command: "{{ item }}"
  with_items:
    - apt-get update
  ignore_errors: yes


- name: install docker
  command: "{{ item }}"
  with_items:
    - apt-get install docker-ce -y

- name: add user in docker group
  command: "{{ item }}"
  with_items:
    - groupadd docker
    - "usermod -aG docker {{ ansible_user }}"
  ignore_errors: yes

- name: copy template config
  template:
    src: daemon.json.j2
    dest: "/etc/docker/daemon.json"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

